# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: LuckyLoop API
            description: Documentaci칩n de la API del proyecto LuckyLoop
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login:
                post:
                    tags:
                        - Autenticaci칩n
                    summary: Obtener token JWT
                    description: Autentica al usuario y devuelve un token JWT
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                            example: usuario@example.com
                                        password:
                                            type: string
                                            example: password123
                                    required:
                                        - email
                                        - password
                    responses:
                        '200':
                            description: Autenticaci칩n correcta
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9...
                                            user:
                                                type: object
                                                properties:
                                                    id:
                                                        type: integer
                                                        example: 1
                                                    email:
                                                        type: string
                                                        example: usuario@example.com
                                                    roles:
                                                        type: array
                                                        items:
                                                            type: string
                                                        example: ["ROLE_USER"]
                                            expires_at:
                                                type: integer
                                                example: 1617638400
                        '401':
                            description: Credenciales inv치lidas
    areas:
        path_patterns:
            - ^/api(?!/doc$)